spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dorm
    username: root
    password: chen1010200220
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  port: 8445
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: chen1010200220
    key-store-type: PKCS12
    key-alias: aliyunSSL